version: '2'
services:
  php:
    image: registry.cn-hangzhou.aliyuncs.com/ytoken/php:6.0
    container_name: php
    tty: true
    volumes:
      - '/home/yangyi/workspace:/var/www/html'
      - './logs:/dev/shm'
      - './php:/etc/php/7.3/fpm/pool.d'
    networks:
      comm:
        aliases:
          - php
    ports:
     - "9000:9000"
  nginx:
    image: nginx:1.15
    container_name: nginx
    tty: true
    volumes_from:
      - php
    volumes:
      - './logs:/var/log/nginx/'
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/ssl:/etc/nginx/ssl'
    networks:
      comm:
        aliases:
          - nginx
    ports:
     - "80:80"
     - "443:443"
  redis:
    image: redis
    container_name: redis
    tty: true
    networks:
      comm:
        aliases:
          - redis
    ports:
      - "127.0.0.1:6379:6379"
  mysql:
    image: mysql:5.6.35
    container_name: mysql
    tty: true
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      comm:
        aliases:
          - mysql
    ports:
      - "127.0.0.1:3307:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=123456
  elasticsearch:
    image: elasticsearch:5.2.2
    container_name: elasticsearch
    tty: true
    volumes:
      - './elasticsearch:/usr/share/elasticsearch/data'
    networks:
      comm:
        aliases:
          - elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
networks:
    comm:
